version: "3.7"
services:
  test:
    image: springcloud/spring-cloud-contract:2.2.0.BUILD-SNAPSHOT
    ports:
      - "5005:5005"
    environment:
      - PUBLISH_ARTIFACTS=false
      - APPLICATION_BASE_URL=http://service:8080/
      - PROJECT_GROUP=com.example
      - PROJECT_VERSION=0.1-SNAPSHOT
      - PROJECT_NAME=custom-contracts
    volumes:
      - "./src/test/resources/contracts/:/contracts:ro"
      - "./build/spring-cloud-contract-output/:/spring-cloud-contract-output/"
      - "./settings.gradle:/spring-cloud-contract/settings.gradle"
      - "./src/main/groovy:/spring-cloud-contract/src/main/groovy"
      - "./src/main/resources/META-INF:/spring-cloud-contract/src/main/resources/META-INF"
      - "./build.gradle:/spring-cloud-contract/build.gradle"
    command: ./gradlew clean compileGroovy processResources generateContractTests --stacktrace -Dorg.gradle.debug=true --no-daemon